name: smart_home
description: app for home automation

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sticky_headers: "^0.1.7"
  animated_background: ^1.0.0
  fluttertoast: ^2.0.7
  material_design_icons_flutter: 3.0.3392
  http: 0.12.0
  shared_preferences: 0.5.0
  device_apps: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/main.jpg
    - assets/logo.png
    - assets/main1.jpg
    - assets/Manual.png
    - assets/Auto.png
    - assets/error.png
    - assets/ip.jpg
    - assets/ip.png
    - assets/fan.png
    - assets/ac.png
    - assets/tvs.png
    - assets/tubelight.png
#    - assets/logo.png
#    - assets/logo.png
  fonts:
    - family: sample
      fonts:
        - asset: assets/sample.ttf
    - family: sample2
      fonts:
        - asset: assets/sample2.ttf
    - family: po
      fonts:
        - asset: assets/po.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
